### ISSUE TITLE
Query Regarding hOCR Generation Using Azure Vision JSON Format

### ISSUE THREAD

**Issue by amehmood-pls** [Azure-Samples/azure-search-power-skills#123] opened 2023-08-08 15:07 UTC
I'm attempting to create the hOCR file by following the instructions outlined on this page (https://learn.microsoft.com/en-us/samples/azure-samples/azure-search-power-skills/azure-hocr-generator-sample/). After deployment, I conducted a successful test using a sample input provided on the same page. However, when I attempted to use a different JSON file that I generated using the Computer Vision API (https://eastus.api.cognitive.microsoft.com/computervision/imageanalysis:analyze?features=read&language=en&gender-neutral-caption=false&api-version=2023-04-01-preview), the hOCR generation process failed due to a disparity in the JSON formats. Does this imply that I always need to convert the JSON output from Azure Vision to match the format expected by the hOCR generator? Alternatively, is there a more straightforward method to directly input the Azure Vision JSON into the hOCR generator?

**Comment by bleroy** [comment] 2023-08-08 17:11
What's the disparity in JSON formats? Can you provide an example? I'd say yes, you need to provide the format the function expects, or modify the function's code to handle the Vision format.

**Comment by amehmood-pls** [comment] 2023-08-08 17:50
Of course, I'm including both payloads (functional and non-functional versions). The non-functional version is produced by the Azure Vision API and contains pages and additional details that are absent in the properly working version generated by the hOCR generator. Additionally, the boundingBox format varies significantly between these two versions.
[working.json.txt](https://github.com/Azure-Samples/azure-search-power-skills/files/12294447/working.json.txt)
[not-working.json.txt](https://github.com/Azure-Samples/azure-search-power-skills/files/12294449/not-working.json.txt)

**Comment by bleroy** [comment] 2023-08-08 18:38
Yes, that looks like a completely different format. You might as well write a new function. That's not what this one was designed for, but it should still provide a good starting point, hopefully. I'm going to close the issue, but please let me know if you need help writing a new function.

**Closed by bleroy** 2023-08-08 18:38 UTC
